### ISSUE TITLE
Setup with generic view instead a cell

### ISSUE THREAD

**Issue by fabiosoft** [LorTos/MatchTransition#1]
I was falling in love with this damn simple pod, but suddently...**oh no!**

I can configure a `Match` between two `UIViews` but not setup with them, only `UICollectionViewCell` or `UITableViewCell` allowed.

I was testing with two `UIImageViews`.

Maybe a more generic initializer could fit better for various situations.

**Comment by LorTos** [comment]
Already thought of something like this, I have something in mind! I'll try and publish an update soon.

Thanks for the feedback!
